// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azthgtmchlqhtzlgwolw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6dGhndG1jaGxxaHR6bGd3b2x3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMjQ5ODksImV4cCI6MjA3MDkwMDk4OX0.h5Cl_qJHDWlnGArMe8pQCn0rwhYUYBcdaviIvpxryAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});